import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { LeftSidebar } from "@/components/common/LeftSideBar";
import { RightSidebar } from "@/components/common/RightSideBar";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        {/* <TRPCReactProvider> */}
        <div className="bg-background flex min-h-screen">
          <LeftSidebar />
          <main className="min-h-screen flex-1 border-l border-r border-border">
            {children}
          </main>
          <RightSidebar />
        </div>
        {/* </TRPCReactProvider> */}
      </body>
    </html>
  );
}
